#!/usr/bin/env node
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const CONFIGS_DIR = path.join(REPO_ROOT, "src", "scrapers", "configs");
const REGISTRY_PATH = path.join(REPO_ROOT, "src", "scrapers", "municipalities.json");

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (!arg.startsWith("--")) continue;
    const [key, inline] = arg.slice(2).split("=");
    args[key] = inline !== undefined ? inline : argv[++i];
  }
  return args;
}

async function detectStack(url) {
  const response = await fetch(url, {
    headers: { "user-agent": "Mozilla/5.0 (compatible; samaniti-data-col)" },
    redirect: "follow",
  });
  if (!response.ok) throw new Error(`HTTP ${response.status}`);
  const html = await response.text();
  if (/wp-content\/|wp-json/i.test(html)) return "wordpress";
  if (/Sites\/default\/files|Drupal\.settings|misc\/drupal\.js/i.test(html)) return "drupal7";
  if (/data-drupal-selector|Drupal\.behaviors/i.test(html)) return "generic";
  return "generic";
}

function configTemplate({ code, codeLower, nameNe, nameEn, province, district, baseUrl, stack }) {
  const exportName = `${code.toUpperCase()}_SITE`;
  return `import path from "node:path";
import { fileURLToPath } from "node:url";
import { SiteConfig } from "../../core/contracts/site-config.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * ${nameEn} (${province}, ${district}) — ${stack} portal.
 * Generated by scripts/new-site.mjs. Verify listPath and selectors against the live site.
 */
export const ${exportName}: SiteConfig = {
  code: "${code}",
  municipality: {
    code: "${code}",
    nameNe: "${nameNe}",
    nameEn: "${nameEn}",
    province: "${province}",
    district: "${district}",
  },
  baseUrl: "${baseUrl}",
  stack: "${stack}",
  mockBaseDir: path.resolve(__dirname, "../mocks/${codeLower}"),
  entities: [
    {
      type: "notice",
      typeLabel: "news_notice",
      listPath: "/en/news-notice",
      detailSelector: "li.node-readmore a",
      detailType: "noticeDetail",
      paginated: true,
    },
  ],
};

export default ${exportName};
`;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const required = ["code", "name-ne", "name-en", "province", "district", "url"];
  const missing = required.filter((key) => !args[key]);
  if (missing.length > 0) {
    console.error(
      `[new-site] Missing required option(s): ${missing.map((m) => `--${m}`).join(", ")}\n` +
        `Usage: node scripts/new-site.mjs --code=KANCHAN --name-ne="..." --name-en="..." --province=Lumbini --district=Rupandehi --url=https://... [--stack=drupal7]`,
    );
    process.exit(1);
  }

  const code = args.code.toUpperCase();
  const codeLower = code.toLowerCase();
  const configPath = path.join(CONFIGS_DIR, `${codeLower}.ts`);

  if (
    await fs
      .access(configPath)
      .then(() => true)
      .catch(() => false)
  ) {
    console.error(`[new-site] Config already exists: ${configPath}`);
    process.exit(1);
  }

  const stack = args.stack || (await detectStack(args.url));
  console.log(`[new-site] Using stack '${stack}' for ${args.url}`);

  const template = configTemplate({
    code,
    codeLower,
    nameNe: args["name-ne"],
    nameEn: args["name-en"],
    province: args.province,
    district: args.district,
    baseUrl: args.url.replace(/\/$/, ""),
    stack,
  });
  await fs.writeFile(configPath, template, "utf-8");
  console.log(`[new-site] Wrote ${path.relative(REPO_ROOT, configPath)}`);

  const registry = JSON.parse(await fs.readFile(REGISTRY_PATH, "utf-8"));
  registry.municipalities = registry.municipalities.filter((m) => m.code !== code);
  registry.municipalities.push({
    code,
    nameNe: args["name-ne"],
    nameEn: args["name-en"],
    province: args.province,
    district: args.district,
    baseUrl: args.url.replace(/\/$/, ""),
    stack,
    config: `./configs/${codeLower}.js`,
    exportName: `${code}_SITE`,
    enabled: true,
  });
  await fs.writeFile(REGISTRY_PATH, `${JSON.stringify(registry, null, 2)}\n`, "utf-8");
  console.log(`[new-site] Registered '${code}' in ${path.relative(REPO_ROOT, REGISTRY_PATH)}`);
  console.log(`[new-site] Next: review the config selectors, then run: npm run scrape -- ${code}`);
}

main().catch((err) => {
  console.error(`[new-site] ${err.message}`);
  process.exit(1);
});
